
import type { Listing } from './types';
import type { Partner } from './partners';

export const MOCK_PARTNERS: Partner[] = [
  // ========== MARRAKECH ==========
  {
    slug: "hertz-marrakech",
    name: "Hertz",
    city: "Marrakech",
    category: "Cars",
    logo: "https://placehold.co/100x100.png",
    verified: true,
    languages: ["EN", "FR", "AR"],
    shortAbout: "Your reliable choice for car rentals in Marrakech. We offer a modern fleet and professional service.",
    longAbout: "Since 2010, Hertz Marrakech has been a leading name in mobility solutions. Our mission is to provide clean, reliable, and affordable vehicles for tourists and business travelers alike. We pride ourselves on our transparent pricing, with no hidden fees and flexible options like no-deposit rentals on many of our economy cars. We understand the importance of customer service and offer 24/7 support via MarHire to handle any of your needs during your rental.",
    policies: {
      deposit: "No-deposit available on selected cars with a small surcharge. A refundable deposit may be required for premium vehicles.",
      fuel: "Same-to-same",
      kilometers: "Unlimited mileage is included for rentals of 3 days or more. Shorter rentals may have a mileage cap.",
      pickupDocs: "Valid driver's license (held for at least 1 year), Passport/ID card, and booking voucher. An International Driving Permit (IDP) is recommended for non-latin alphabet licenses.",
      changes: "To change or cancel your booking, please contact MarHire support via email or WhatsApp.",
      intercity: "One-way rentals to other major Moroccan cities are possible but may incur an additional fee.",
      crossBorder: "Not allowed",
    },
    openingHours: ["Mon–Sun 08:00–22:00"],
  },
  {
    slug: "avis-marrakech",
    name: "Avis",
    city: "Marrakech",
    category: "Cars",
    logo: "https://placehold.co/100x100.png",
    verified: true,
    languages: ["EN", "FR"],
    shortAbout: "Global standards with local expertise for your Marrakech car rental needs.",
    longAbout: "Avis Marrakech brings world-class service to the heart of Morocco. We offer a wide range of vehicles, from economical city cars to rugged SUVs perfect for exploring the Atlas mountains. Our commitment is to quality, safety, and customer satisfaction, ensuring your rental experience is smooth and hassle-free from start to finish.",
    policies: {
      deposit: "A refundable security deposit is standard. Please check the listing for no-deposit options on specific models.",
      fuel: "Same-to-same",
      kilometers: "Unlimited kilometers are offered on most of our fleet to encourage boundless exploration.",
      pickupDocs: "Driver's license, Passport/ID, and MarHire booking confirmation are required.",
      changes: "All booking modifications must be processed through MarHire's central support.",
      intercity: "Intercity rentals can be arranged upon request. Please contact support for availability and pricing.",
      crossBorder: "Not allowed",
    },
    openingHours: ["Mon–Sun 08:00–20:00"],
  },
  {
    slug: "marrakech-premium-drivers",
    name: "Marrakech Premium",
    city: "Marrakech",
    category: "Private Drivers",
    logo: "https://placehold.co/100x100.png",
    verified: true,
    languages: ["EN", "FR", "AR", "ES"],
    shortAbout: "Luxury vehicles and professional chauffeurs for airport transfers, city tours, and business travel in Marrakech.",
    longAbout: "Experience Marrakech in comfort and style with Marrakech Premium. Our fleet of modern, high-end vehicles like the Mercedes V-Class ensures a smooth and comfortable journey. Our drivers are not just drivers; they are professional, multilingual hosts dedicated to providing impeccable service. Whether you need a reliable airport transfer or a bespoke tour of the city's landmarks, we are at your service.",
    policies: {
      deposit: "No deposit required for standard transfer and tour services.",
      fuel: "Same-to-same",
      kilometers: "Pricing is based on the agreed-upon trip or service, not on mileage.",
      pickupDocs: "The lead passenger should have a form of ID and the MarHire booking voucher.",
      changes: "Please contact MarHire support for any changes to your pickup time or location.",
      intercity: "We specialize in comfortable and reliable intercity transfers to all major destinations in Morocco.",
      crossBorder: "Not allowed",
    },
    openingHours: ["Available 24/7"],
  },
  {
    slug: "atlas-expeditions-marrakech",
    name: "Atlas Expeditions",
    city: "Marrakech",
    category: "Private Drivers",
    logo: "https://placehold.co/100x100.png",
    verified: true,
    languages: ["EN", "ES", "BER"],
    shortAbout: "Specialists in Atlas Mountains day trips and desert excursions with experienced local drivers.",
    longAbout: "Atlas Expeditions connects you with the raw beauty of Morocco's landscapes. Our experienced drivers are also knowledgeable guides who can show you the hidden gems of the Atlas Mountains and beyond. We use comfortable 4x4 vehicles like the Toyota Land Cruiser, perfect for navigating scenic mountain roads. Your safety and authentic experience are our priorities.",
    policies: {
      deposit: "No deposit is required for our day trips and tours.",
      fuel: "Same-to-same",
      kilometers: "Pricing is all-inclusive for the planned itinerary.",
      pickupDocs: "Your booking confirmation is all you need.",
      changes: "Contact MarHire support to adjust your booking.",
      intercity: "Multi-day tours and intercity transfers are our specialty.",
      crossBorder: "Not allowed",
    },
    openingHours: ["Mon–Sun 08:00–19:00"],
  },
   {
    slug: "marrakech-lake-sports",
    name: "Marrakech Lake Sports",
    city: "Marrakech",
    category: "Boats",
    logo: "https://placehold.co/100x100.png",
    verified: true,
    languages: ["EN", "FR"],
    shortAbout: "Experience the best water sports and activities at Lalla Takerkoust lake, just outside Marrakech.",
    longAbout: "Escape the city heat with Marrakech Lake Sports! We are the premier provider of water-based activities on the stunning Lalla Takerkoust lake. From high-speed jet ski rentals to relaxing pontoon boat cruises, we offer a unique way to experience the beauty of the Atlas foothills. Our team is composed of certified instructors and skippers who prioritize your safety above all else. All our equipment is modern and well-maintained, and safety gear is always included.",
     policies: {
      deposit: "A small refundable deposit may be required for jet ski rentals, payable on site.",
      fuel: "Same-to-same", 
      kilometers: "N/A",
      pickupDocs: "Passport/ID card and booking voucher.",
      changes: "To change or cancel your activity, please contact MarHire support. Weather-related cancellations can be rescheduled free of charge.",
      intercity: "N/A",
      crossBorder: "Not allowed",
    },
    openingHours: ["Mon–Sun 10:00–18:00 (Weather permitting)"],
  },
  {
    slug: "atlas-lake-adventures-marrakech",
    name: "Atlas Lake Adventures",
    city: "Marrakech",
    category: "Boats",
    logo: "https://placehold.co/100x100.png",
    verified: true,
    languages: ["EN", "FR", "AR"],
    shortAbout: "Family-friendly boat trips and paddleboard rentals on Lalla Takerkoust lake.",
    longAbout: "Enjoy a day of fun and relaxation with Atlas Lake Adventures. We offer a variety of activities perfect for families and groups, including pedal boats, kayaks, and guided pontoon tours with stunning views of the Atlas Mountains. Our focus is on safe, accessible fun for everyone.",
    policies: {
      deposit: "No deposit required for our guided tours and standard rentals.",
      fuel: "Same-to-same",
      kilometers: "N/A",
      pickupDocs: "Booking confirmation from MarHire.",
      changes: "Contact MarHire support for any booking adjustments. We reschedule for free in case of bad weather.",
      intercity: "N/A",
      crossBorder: "Not allowed",
    },
    openingHours: ["Mon–Sun 09:30–18:30"],
  },
  {
    slug: 'marrakech-guided-tours',
    name: 'Marrakech Guided Tours',
    city: 'Marrakech',
    category: 'Activities',
    logo: 'https://placehold.co/100x100.png',
    verified: true,
    languages: ["EN", "FR", "ES"],
    shortAbout: 'Official licensed guides for immersive walking tours of Marrakech\'s historic medina and souks.',
    longAbout: 'Discover the secrets of the Red City with our team of passionate, licensed guides. We take you beyond the surface to explore the rich history, vibrant culture, and hidden corners of Marrakech. Our tours are designed to be informative, engaging, and respectful of local traditions. We offer both small group and private experiences to suit your travel style.',
    policies: {
      deposit: 'No deposit required.',
      fuel: 'Same-to-same',
      kilometers: 'N/A',
      pickupDocs: 'Booking voucher and a curious mind.',
      changes: 'Contact MarHire support. Free cancellation up to 24 hours before the tour.',
      intercity: 'N/A',
      crossBorder: 'Not allowed',
    },
    openingHours: ["Mon–Sat 09:00–17:00"],
  },
  {
    slug: 'agafay-desert-adventures',
    name: 'Agafay Desert Adventures',
    city: 'Marrakech',
    category: 'Activities',
    logo: 'https://placehold.co/100x100.png',
    verified: true,
    languages: ["EN", "FR", "ES"],
    shortAbout: 'Exciting quad biking, camel rides, and buggy tours in the Agafay desert near Marrakech.',
    longAbout: 'Discover the thrill of the Moroccan outdoors with Agafay Desert Adventures. We offer a range of guided tours suitable for all levels, from beginners to experienced riders. Safety is our priority, with full equipment and expert guides included in every tour. Join us for an unforgettable adventure!',
    policies: {
      deposit: 'No deposit required.',
      fuel: 'Same-to-same',
      kilometers: 'N/A',
      pickupDocs: 'Booking voucher and ID.',
      changes: 'Contact MarHire support. Free rescheduling for cancellations due to bad weather.',
      intercity: 'N/A',
      crossBorder: 'Not allowed',
    },
     openingHours: ["Mon–Sun 09:00–19:00"],
  },

  // ========== AGADIR ==========
  {
    slug: "europcar-agadir",
    name: "Europcar",
    city: "Agadir",
    category: "Cars",
    logo: "https://placehold.co/100x100.png",
    verified: true,
    languages: ["EN", "FR", "DE"],
    shortAbout: "The best car rental deals at Agadir airport and city center. Wide range of vehicles available.",
    longAbout: "Europcar Agadir offers a seamless rental experience, whether you're arriving at Al Massira Airport or staying in the city. Our diverse fleet ranges from compact cars for city driving to spacious SUVs for family trips along the coast. We are committed to providing excellent value, with competitive pricing and clear policies. Our team is dedicated to getting you on the road quickly and safely.",
    policies: {
      deposit: "A refundable security deposit is required on a credit card. No-deposit options may be available with full insurance packages.",
      fuel: "Same-to-same",
      kilometers: "Most of our rentals include unlimited mileage for maximum freedom to explore the Souss-Massa region.",
      pickupDocs: "Valid driver's license, Passport/ID, and booking confirmation. An IDP is recommended.",
      changes: "All booking changes must be handled through MarHire's central support team.",
      intercity: "One-way rentals to cities like Marrakech or Essaouira can be arranged. Please contact support for a quote.",
      crossBorder: "Not allowed",
    },
    openingHours: ["Mon–Sun 07:00–23:00"],
  },
  {
    slug: "4x4-morocco-agadir",
    name: "4x4 Morocco",
    city: "Agadir",
    category: "Cars",
    logo: "https://placehold.co/100x100.png",
    verified: true,
    languages: ["EN", "FR"],
    shortAbout: "Specialists in 4x4 and SUV rentals for your Moroccan adventures.",
    longAbout: "For those looking to explore off the beaten path, 4x4 Morocco in Agadir provides robust and reliable vehicles like the Jeep Wrangler. Our fleet is perfectly suited for the diverse terrain of the region, from coastal tracks to mountain passes. We provide thorough vehicle briefings and support to ensure your adventure is both exciting and safe.",
    policies: {
      deposit: "A security deposit is required for all 4x4 vehicles.",
      fuel: "Same-to-same",
      kilometers: "Limited mileage is standard to ensure vehicle maintenance, with options to purchase additional kilometers.",
      pickupDocs: "Valid driver's license, Passport/ID, and booking voucher. Off-road experience is a plus.",
      changes: "Contact MarHire support for any booking adjustments.",
      intercity: "One-way rentals can be arranged subject to availability.",
      crossBorder: "Not allowed",
    },
    openingHours: ["Mon–Sat 09:00–18:00"],
  },
  {
    slug: "agadir-shuttle-service",
    name: "Agadir Shuttle",
    city: "Agadir",
    category: "Private Drivers",
    logo: "https://placehold.co/100x100.png",
    verified: true,
    languages: ["EN", "FR", "DE"],
    shortAbout: "Reliable and affordable private transfers from Agadir airport to hotels, Taghazout, and beyond.",
    longAbout: "Agadir Shuttle provides punctual and professional driver services for individuals and groups. We specialize in airport transfers, ensuring a stress-free start to your holiday. Our drivers monitor your flight for any delays and will be waiting for you in the arrivals hall. We use modern, air-conditioned vehicles like the Ford Tourneo to guarantee a comfortable ride for you and your luggage.",
    policies: {
      deposit: "No deposit is required for our services.",
      fuel: "Same-to-same",
      kilometers: "All prices are fixed for the specified route, regardless of traffic or duration.",
      pickupDocs: "Please have your booking confirmation ready to show the driver.",
      changes: "To modify your booking, please contact MarHire's central support team.",
      intercity: "We offer fixed-price transfers to many destinations, including Marrakech and Essaouira.",
      crossBorder: "Not allowed",
    },
    openingHours: ["Available 24/7"],
  },
  {
    slug: "essaouira-drives-agadir",
    name: "Essaouira Drives",
    city: "Agadir",
    category: "Private Drivers",
    logo: "https://placehold.co/100x100.png",
    verified: true,
    languages: ["EN", "FR"],
    shortAbout: "Comfortable private transfers and coastal tours between Agadir and Essaouira.",
    longAbout: "Specializing in the scenic coastal route, Essaouira Drives offers a relaxing and enjoyable alternative to self-driving. Our professional drivers know the best photo stops and points of interest along the way. Travel in a comfortable SUV and enjoy the ride.",
    policies: {
      deposit: "No deposit needed for transfers.",
      fuel: "Same-to-same",
      kilometers: "Price is fixed for the selected route.",
      pickupDocs: "Your booking confirmation.",
      changes: "Contact MarHire support for changes.",
      intercity: "We specialize in the Agadir-Essaouira route and can accommodate other requests.",
      crossBorder: "Not allowed",
    },
    openingHours: ["Mon–Sun 08:00–20:00"],
  },
  {
    slug: "agadir-cruises",
    name: "Agadir Cruises",
    city: "Agadir",
    category: "Boats",
    logo: "https://placehold.co/100x100.png",
    verified: true,
    languages: ["EN", "FR", "AR"],
    shortAbout: "Classic yacht tours and private boat rentals from the Agadir Marina.",
    longAbout: "Set sail on the Atlantic with Agadir Cruises. We offer a range of boat trips, from shared day tours with lunch to private luxury yacht charters for special occasions. Our experienced captains and crew know the best spots along the coast for swimming, fishing, or simply enjoying the sunset. Your safety and enjoyment are our main concerns.",
    policies: {
      deposit: "No deposit required for standard tours. A deposit may be needed for private, multi-day charters.",
      fuel: "Same-to-same",
      kilometers: "N/A",
      pickupDocs: "ID and booking voucher are required at the marina.",
      changes: "Contact MarHire support for any changes. Trips cancelled due to bad weather will be fully refunded or rescheduled.",
      intercity: "N/A",
      crossBorder: "Not allowed",
    },
     openingHours: ["Mon–Sun 09:00–19:00"],
  },
  {
    slug: "agadir-party-boats",
    name: "Agadir Party Boats",
    city: "Agadir",
    category: "Boats",
    logo: "https://placehold.co/100x100.png",
    verified: true,
    languages: ["EN", "FR"],
    shortAbout: "The ultimate party experience on the water with music, food, and fun.",
    longAbout: "Agadir Party Boats is the perfect choice for celebrations, group outings, or just a fun day on the ocean. Our large, stable boats are equipped with sound systems and plenty of space to dance. Our crew is dedicated to creating a vibrant and safe atmosphere for all our guests.",
    policies: {
      deposit: "A group deposit is required for private party charters.",
      fuel: "Same-to-same",
      kilometers: "N/A",
      pickupDocs: "Booking confirmation for the group leader.",
      changes: "Changes to private charters require advance notice through MarHire support.",
      intercity: "N/A",
      crossBorder: "Not allowed",
    },
    openingHours: ["Bookings available day & night"],
  },
  {
    slug: 'surf-berbere-taghazout',
    name: 'Surf Berbere',
    city: 'Agadir',
    category: 'Activities',
    logo: 'https://placehold.co/100x100.png',
    verified: true,
    languages: ["EN", "FR"],
    shortAbout: 'Learn to surf at one of the world\'s most famous surf spots. Lessons for all levels in Taghazout.',
    longAbout: 'Join the tribe at Surf Berbere, one of the original surf schools in Taghazout. Our certified instructors provide lessons for absolute beginners, intermediate surfers looking to improve, and advanced surfers wanting to discover the best local breaks. We provide all the equipment (board, wetsuit) and a fun, safe environment to catch your first wave or master your technique.',
    policies: {
      deposit: 'No deposit required.',
      fuel: 'Same-to-same',
      kilometers: 'N/A',
      pickupDocs: 'Booking voucher.',
      changes: 'Contact MarHire support to make changes to your booking. We offer flexible rescheduling.',
      intercity: 'N/A',
      crossBorder: 'Not allowed',
    },
    openingHours: ["Mon–Sun 09:00–17:00"],
  },
  {
    slug: 'agadir-adventures-team',
    name: 'Agadir Adventures',
    city: 'Agadir',
    category: 'Activities',
    logo: 'https://placehold.co/100x100.png',
    verified: true,
    languages: ["EN", "FR", "DE"],
    shortAbout: 'Paradise Valley tours, sandboarding, and buggy adventures from Agadir.',
    longAbout: 'Explore the diverse landscapes around Agadir with our range of day trips and activities. From the lush pools of Paradise Valley to the sand dunes of Taboga, our local guides will take you on an unforgettable journey. We offer hotel pickups and all-inclusive packages for a hassle-free experience.',
    policies: {
      deposit: 'No deposit required for day trips.',
      fuel: 'Same-to-same',
      kilometers: 'N/A',
      pickupDocs: 'Your MarHire booking confirmation.',
      changes: 'Contact MarHire support for any changes. Free cancellation available.',
      intercity: 'N/A',
      crossBorder: 'Not allowed',
    },
    openingHours: ["Mon–Sun 08:30–18:00"],
  },
  
  // ========== CASABLANCA ==========
  {
    slug: "sixt-casablanca",
    name: "Sixt",
    city: "Casablanca",
    category: "Cars",
    logo: "https://placehold.co/100x100.png",
    verified: true,
    languages: ["EN", "FR", "AR"],
    shortAbout: "Premium car rentals in Casablanca for business and leisure travelers.",
    longAbout: "Sixt Casablanca offers a premium rental experience with a fleet of well-maintained, modern vehicles. From business sedans to family cars, we provide top-tier service, easy airport pickup, and a commitment to customer satisfaction. Experience the best of Casablanca with a reliable car from Sixt.",
    policies: {
      deposit: "A refundable security deposit is required on a credit card.",
      fuel: "Same-to-same",
      kilometers: "Generous mileage allowances with unlimited options available.",
      pickupDocs: "Valid driver's license, Passport/ID, and booking voucher.",
      changes: "All booking modifications must be handled through MarHire's central support team.",
      intercity: "One-way rentals are available to other major hubs like Marrakech and Rabat.",
      crossBorder: "Not allowed",
    },
    openingHours: ["Available 24/7"],
  },
  {
    slug: "local-drive-casablanca",
    name: "Local Drive",
    city: "Casablanca",
    category: "Cars",
    logo: "https://placehold.co/100x100.png",
    verified: false,
    languages: ["FR", "AR"],
    shortAbout: "Affordable and straightforward car rentals with a personal touch.",
    longAbout: "Local Drive is your friendly neighborhood car rental in Casablanca. We focus on providing simple, affordable, and reliable cars like the Fiat 500. We believe in great value and transparent service, making us a favorite for budget-conscious travelers.",
    policies: {
      deposit: "No-deposit options are our specialty, especially for economy cars.",
      fuel: "Same-to-same",
      kilometers: "Unlimited kilometers are standard on most rentals.",
      pickupDocs: "Driver's license, ID, and booking confirmation.",
      changes: "Contact MarHire support to make changes to your booking.",
      intercity: "Please inquire about our one-way rental availability.",
      crossBorder: "Not allowed",
    },
    openingHours: ["Mon–Sat 09:00–19:00"],
  },
  {
    slug: "casablanca-vip",
    name: "Casablanca VIP",
    city: "Casablanca",
    category: "Private Drivers",
    logo: "https://placehold.co/100x100.png",
    verified: true,
    languages: ["EN", "FR"],
    shortAbout: "Executive chauffeur services in Casablanca with luxury vehicles.",
    longAbout: "Casablanca VIP provides discreet and professional chauffeur services for discerning clients. Our fleet includes luxury vehicles like the Range Rover Vogue, and our drivers are trained to provide the highest level of service. We are the perfect choice for business travel, special events, and VIP airport transfers.",
    policies: {
      deposit: "No deposit needed.",
      fuel: "Same-to-same",
      kilometers: "Priced per service.",
      pickupDocs: "Booking confirmation.",
      changes: "Contact MarHire for modifications.",
      intercity: "Available for premium inter-city travel.",
      crossBorder: "Not allowed",
    },
    openingHours: ["Available 24/7"],
  },
  {
    slug: "morocco-direct-casablanca",
    name: "Morocco Direct",
    city: "Casablanca",
    category: "Private Drivers",
    logo: "https://placehold.co/100x100.png",
    verified: false,
    languages: ["AR", "FR"],
    shortAbout: "No-frills, reliable private transfers for inter-city travel from Casablanca.",
    longAbout: "Morocco Direct offers an efficient and cost-effective solution for traveling between cities. We use comfortable sedans like the Skoda Octavia and focus on providing a safe and direct journey to your destination. Ideal for travelers who value efficiency and affordability.",
    policies: {
      deposit: "No deposit.",
      fuel: "Same-to-same",
      kilometers: "Fixed price per route.",
      pickupDocs: "Booking voucher.",
      changes: "Contact MarHire support.",
      intercity: "This is our specialty.",
      crossBorder: "Not allowed",
    },
    openingHours: ["Mon–Sun 07:00–22:00"],
  },
  {
    slug: "atlantic-fishing-casablanca",
    name: "Atlantic Fishing",
    city: "Casablanca",
    category: "Boats",
    logo: "https://placehold.co/100x100.png",
    verified: true,
    languages: ["FR", "ES", "AR"],
    shortAbout: "Professional deep-sea fishing charters leaving from Casablanca.",
    longAbout: "Join our experienced crew for an exciting day of fishing on the Atlantic. We provide all the gear, bait, and expertise you need to land a great catch. Our boats are equipped with modern fishing technology and safety equipment. Suitable for both seasoned anglers and beginners.",
    policies: {
      deposit: "A deposit is required to reserve a private charter.",
      fuel: "Same-to-same",
      kilometers: "N/A",
      pickupDocs: "Booking confirmation.",
      changes: "Contact MarHire support. Weather cancellations are rescheduled or refunded.",
      intercity: "N/A",
      crossBorder: "Not allowed",
    },
    openingHours: ["Trips depart early morning, 06:00-15:00"],
  },
  {
    slug: "casa-nautic",
    name: "Casa Nautic",
    city: "Casablanca",
    category: "Boats",
    logo: "https://placehold.co/100x100.png",
    verified: false,
    languages: ["FR", "AR"],
    shortAbout: "Leisurely boat tours and coastal cruises from the Casablanca marina.",
    longAbout: "See Casablanca from a different perspective with Casa Nautic. We offer relaxing coastal tours that showcase the city's impressive skyline, including the Hassan II Mosque. Our trips are perfect for families, couples, and anyone looking for a peaceful escape on the water.",
    policies: {
      deposit: "No deposit for standard tours.",
      fuel: "Same-to-same",
      kilometers: "N/A",
      pickupDocs: "Booking voucher.",
      changes: "Contact MarHire support.",
      intercity: "N/A",
      crossBorder: "Not allowed",
    },
    openingHours: ["Mon-Sun 10:00-19:00"],
  },
  {
    slug: "casablanca-city-tours",
    name: "Casablanca City Tours",
    city: "Casablanca",
    category: "Activities",
    logo: "https://placehold.co/100x100.png",
    verified: true,
    languages: ["EN", "FR"],
    shortAbout: "Guided tours of Casablanca's most iconic landmarks, including the Hassan II Mosque.",
    longAbout: "Explore the architectural wonders and vibrant culture of Morocco's economic capital. Our guided tours provide fascinating insights into landmarks like the Hassan II Mosque, the old medina, and the Art Deco district. Let our knowledgeable guides show you the real Casablanca.",
    policies: {
      deposit: "No deposit necessary.",
      fuel: "Same-to-same",
      kilometers: "N/A",
      pickupDocs: "Booking confirmation.",
      changes: "Contact MarHire support.",
      intercity: "N/A",
      crossBorder: "Not allowed",
    },
    openingHours: ["Tours at 10:00 and 14:00 daily"],
  },
  {
    slug: "casa-food-tours",
    name: "Casa Food Tours",
    city: "Casablanca",
    category: "Activities",
    logo: "https://placehold.co/100x100.png",
    verified: false,
    languages: ["EN", "FR"],
    shortAbout: "Taste your way through Casablanca with our guided culinary walking tours.",
    longAbout: "Dive into the delicious world of Moroccan cuisine with Casa Food Tours. We take you to authentic local eateries, bustling markets, and hidden gems to sample the best street food and traditional dishes the city has to offer. It's a feast for all the senses.",
    policies: {
      deposit: "No deposit.",
      fuel: "Same-to-same",
      kilometers: "N/A",
      pickupDocs: "Your appetite and booking confirmation.",
      changes: "Contact MarHire support.",
      intercity: "N/A",
      crossBorder: "Not allowed",
    },
    openingHours: ["Tours start at 11:00 and 18:00"],
  },

  // ========== FES ==========
  {
    slug: "budget-fes",
    name: "Budget",
    city: "Fes",
    category: "Cars",
    logo: "https://placehold.co/100x100.png",
    verified: true,
    languages: ["FR", "AR"],
    shortAbout: "Great value car rentals in Fes, perfect for exploring the city and surrounding areas.",
    longAbout: "Budget Fes offers affordable and reliable car rentals for every traveler. We provide a range of well-maintained vehicles, from economy models to family-sized cars. Our friendly staff at Fes-Saïss Airport will get you on your way quickly so you can start your Moroccan adventure.",
    policies: {
      deposit: "A standard deposit is required. Check listings for details.",
      fuel: "Same-to-same",
      kilometers: "Limited mileage on basic rentals, with unlimited options available.",
      pickupDocs: "Valid driver's license, Passport/ID, and booking voucher.",
      changes: "Please contact MarHire support for any booking modifications.",
      intercity: "One-way rentals can be arranged to other major cities.",
      crossBorder: "Not allowed",
    },
    openingHours: ["Mon–Sun 08:00–21:00"],
  },
  {
    slug: "fez-rent",
    name: "Fez Rent",
    city: "Fes",
    category: "Cars",
    logo: "https://placehold.co/100x100.png",
    verified: false,
    languages: ["FR", "AR"],
    shortAbout: "Local car rental agency in Fes with a focus on no-deposit options.",
    longAbout: "Fez Rent is a local agency dedicated to providing flexible and hassle-free car rentals. We specialize in offering no-deposit options on popular cars like the Dacia Logan, making it easier for you to rent without a large hold on your credit card. We offer friendly service and great local knowledge.",
    policies: {
      deposit: "No-deposit rentals are our specialty.",
      fuel: "Same-to-same",
      kilometers: "Unlimited kilometers included with most rentals.",
      pickupDocs: "Driver's license, ID, and booking confirmation.",
      changes: "Contact MarHire support to make changes.",
      intercity: "Inquire about our one-way rental options.",
      crossBorder: "Not allowed",
    },
    openingHours: ["Mon–Sat 09:00–18:00"],
  },
  {
    slug: "fez-executive",
    name: "Fez Executive",
    city: "Fes",
    category: "Private Drivers",
    logo: "https://placehold.co/100x100.png",
    verified: true,
    languages: ["FR", "AR"],
    shortAbout: "Professional driver services for day trips to Meknes, Volubilis, and Chefchaouen.",
    longAbout: "Explore the rich history surrounding Fes with Fez Executive. We provide comfortable vehicles like the Mercedes S-Class and professional drivers for private day trips to the imperial city of Meknes, the Roman ruins of Volubilis, and the blue city of Chefchaouen. Travel in comfort and style.",
    policies: {
      deposit: "No deposit.",
      fuel: "Same-to-same",
      kilometers: "Fixed price per tour.",
      pickupDocs: "Booking confirmation.",
      changes: "Contact MarHire support.",
      intercity: "Day trips and intercity transfers are our core business.",
      crossBorder: "Not allowed",
    },
    openingHours: ["Mon–Sun 08:00–19:00"],
  },
  {
    slug: "fes-airport-transfers",
    name: "Fes Airport Transfers",
    city: "Fes",
    category: "Private Drivers",
    logo: "https://placehold.co/100x100.png",
    verified: false,
    languages: ["FR", "AR", "EN"],
    shortAbout: "Punctual and reliable airport transfers from Fes-Saïss Airport to your Riad or Hotel.",
    longAbout: "Start your trip to Fes without any stress. Our drivers will meet you at Fes-Saïss Airport, assist with your luggage, and navigate the narrow streets of the medina to get you as close as possible to your accommodation. We offer fixed pricing and reliable service.",
    policies: {
      deposit: "No deposit required.",
      fuel: "Same-to-same",
      kilometers: "Fixed price for airport transfers.",
      pickupDocs: "Your booking confirmation.",
      changes: "Contact MarHire support.",
      intercity: "Also available for transfers to Meknes and other nearby towns.",
      crossBorder: "Not allowed",
    },
    openingHours: ["Available 24/7"],
  },
  {
    slug: "local-river-tours-fes",
    name: "Local River Tours",
    city: "Fes",
    category: "Boats",
    logo: "https://placehold.co/100x100.png",
    verified: false,
    languages: ["FR", "AR"],
    shortAbout: "Relaxing traditional boat rides on the Sebou River, a short drive from Fes.",
    longAbout: "Take a break from the bustling medina and enjoy a peaceful boat ride on the Sebou River. Our traditional felucca-style boats offer a unique and relaxing experience, providing a different perspective on the Moroccan landscape. Perfect for a calm afternoon.",
    policies: {
      deposit: "No deposit.",
      fuel: "Same-to-same",
      kilometers: "N/A",
      pickupDocs: "Booking voucher.",
      changes: "Contact MarHire support.",
      intercity: "N/A",
      crossBorder: "Not allowed",
    },
    openingHours: ["Weekends 11:00–17:00"],
  },
  {
    slug: "sidi-chahed-dam-cruises-fes",
    name: "Sidi Chahed Dam Cruises",
    city: "Fes",
    category: "Boats",
    logo: "https://placehold.co/100x100.png",
    verified: false,
    languages: ["FR", "AR"],
    shortAbout: "Leisurely cruises and pedal boat rentals at the scenic Sidi Chahed dam.",
    longAbout: "Discover the beautiful Sidi Chahed reservoir, a popular recreational spot near Fes. We offer leisurely cruises and pedal boat rentals, perfect for a family outing or a relaxing day in nature. Enjoy the calm waters and scenic views.",
    policies: {
      deposit: "No deposit for rentals.",
      fuel: "Same-to-same",
      kilometers: "N/A",
      pickupDocs: "Booking confirmation.",
      changes: "Contact MarHire support.",
      intercity: "N/A",
      crossBorder: "Not allowed",
    },
    openingHours: ["Fri–Sun 10:00–18:00"],
  },
  {
    slug: "fez-artisanal-tours",
    name: "Fez Artisanal Tours",
    city: "Fes",
    category: "Activities",
    logo: "https://placehold.co/100x100.png",
    verified: true,
    languages: ["EN", "FR"],
    shortAbout: "Private tours of the Fes tanneries and artisan workshops with a focus on cultural heritage.",
    longAbout: "Go behind the scenes of Fes's ancient crafts with our specialized artisanal tours. We provide respectful and insightful visits to the famous Chouara Tannery and other workshops where you can see artisans at work. Our private tours ensure a personal and unhurried experience.",
    policies: {
      deposit: "No deposit required.",
      fuel: "Same-to-same",
      kilometers: "N/A",
      pickupDocs: "Booking confirmation.",
      changes: "Contact MarHire support.",
      intercity: "N/A",
      crossBorder: "Not allowed",
    },
    openingHours: ["Mon–Sat 09:00–16:00"],
  },
  {
    slug: "desert-dreams-fes",
    name: "Desert Dreams",
    city: "Fes",
    category: "Activities",
    logo: "https://placehold.co/100x100.png",
    verified: true,
    languages: ["EN", "FR", "ES"],
    shortAbout: "Multi-day trips from Fes to the Sahara desert at Merzouga, including camping and camel trekking.",
    longAbout: "Embark on the adventure of a lifetime with our guided tours from Fes to the golden dunes of Merzouga. Our packages include transportation, accommodation in a traditional desert camp, camel trekking, and local meals. Experience the magic of the Sahara under the stars.",
    policies: {
      deposit: "A deposit is required to secure multi-day tour bookings.",
      fuel: "Same-to-same",
      kilometers: "N/A",
      pickupDocs: "Booking voucher and passport.",
      changes: "Changes require advance notice via MarHire support.",
      intercity: "N/A",
      crossBorder: "Not allowed",
    },
    openingHours: ["Tours depart daily"],
  },

  // ========== TANGIER ==========
  {
    slug: "green-mobility-tangier",
    name: "Green Mobility",
    city: "Tangier",
    category: "Cars",
    logo: "https://placehold.co/100x100.png",
    verified: true,
    languages: ["EN", "FR", "ES"],
    shortAbout: "Eco-friendly car rentals in Tangier, including electric and hybrid models.",
    longAbout: "Drive sustainably with Green Mobility. We are Tangier's first eco-friendly car rental agency, offering a fleet of electric and hybrid vehicles like the Tesla Model 3. Enjoy a smooth, silent ride while minimizing your carbon footprint. We provide charging information and support for all our electric vehicles.",
    policies: {
      deposit: "A security deposit is required for our specialized fleet.",
      fuel: "Same-to-same",
      kilometers: "Unlimited kilometers are standard.",
      pickupDocs: "Valid driver's license, Passport/ID, and booking voucher.",
      changes: "Contact MarHire support for any booking modifications.",
      intercity: "One-way rentals are available.",
      crossBorder: "Not allowed",
    },
    openingHours: ["Mon–Sun 09:00–20:00"],
  },
  {
    slug: "tangier-easy-rent",
    name: "Tangier Easy Rent",
    city: "Tangier",
    category: "Cars",
    logo: "https://placehold.co/100x100.png",
    verified: false,
    languages: ["FR", "ES", "AR"],
    shortAbout: "Quick and easy car rentals near the Tangier port and medina.",
    longAbout: "Tangier Easy Rent lives up to its name by providing a fast, simple, and affordable rental process. We offer a range of compact and economy cars, perfect for navigating the city. Our location near the port is ideal for travelers arriving by ferry. We pride ourselves on our quick service and competitive local prices.",
    policies: {
      deposit: "Low deposit and no-deposit options are available.",
      fuel: "Same-to-same",
      kilometers: "Limited mileage with options to upgrade.",
      pickupDocs: "Driver's license, ID, and booking voucher.",
      changes: "Contact MarHire support.",
      intercity: "Please inquire for one-way rental availability.",
      crossBorder: "Not allowed",
    },
    openingHours: ["Mon–Sun 08:00–22:00"],
  },
  {
    slug: "tangier-connect",
    name: "Tangier Connect",
    city: "Tangier",
    category: "Private Drivers",
    logo: "https://placehold.co/100x100.png",
    verified: true,
    languages: ["EN", "FR", "ES"],
    shortAbout: "Professional drivers for corporate travel, city tours, and transfers to Chefchaouen.",
    longAbout: "Tangier Connect offers premium driver services with a fleet of comfortable sedans like the BMW 5 Series. Our drivers are professional, discreet, and knowledgeable, making us the ideal choice for business travelers and tourists seeking a higher standard of service. We specialize in transfers from Tangier to Chefchaouen and other popular destinations.",
    policies: {
      deposit: "No deposit required.",
      fuel: "Same-to-same",
      kilometers: "Fixed price per service.",
      pickupDocs: "Booking confirmation.",
      changes: "Contact MarHire support.",
      intercity: "Yes, this is a core part of our service.",
      crossBorder: "Not allowed",
    },
    openingHours: ["Available 24/7"],
  },
  {
    slug: "gibraltar-strait-tours",
    name: "Gibraltar Strait Tours",
    city: "Tangier",
    category: "Private Drivers",
    logo: "https://placehold.co/100x100.png",
    verified: false,
    languages: ["EN", "ES"],
    shortAbout: "Guided driving tours of Cap Spartel and the Caves of Hercules.",
    longAbout: "See the famous sights where the Atlantic meets the Mediterranean with our guided driving tours. Our local driver-guides will take you to Cap Spartel and the Caves of Hercules, sharing stories and history along the way. It's the most comfortable and informative way to see these natural wonders.",
    policies: {
      deposit: "No deposit.",
      fuel: "Same-to-same",
      kilometers: "Price is for the complete tour.",
      pickupDocs: "Booking confirmation.",
      changes: "Contact MarHire support.",
      intercity: "Focus on local tours, but other trips can be arranged.",
      crossBorder: "Not allowed",
    },
    openingHours: ["Mon–Sun 09:00–18:00"],
  },
  {
    slug: "tangier-water-sports",
    name: "Tangier Water Sports",
    city: "Tangier",
    category: "Boats",
    logo: "https://placehold.co/100x100.png",
    verified: false,
    languages: ["EN", "FR", "ES"],
    shortAbout: "Thrilling speedboat adventures and jet ski rentals in the Bay of Tangier.",
    longAbout: "Get your adrenaline pumping with Tangier Water Sports. We offer powerful speedboat and jet ski rentals for you to enjoy the beautiful Bay of Tangier. Safety is our priority, and our team provides full instruction and supervision to ensure you have a fun and secure time on the water.",
    policies: {
      deposit: "A refundable deposit is required for rentals.",
      fuel: "Same-to-same",
      kilometers: "N/A",
      pickupDocs: "ID and booking confirmation.",
      changes: "Contact MarHire support.",
      intercity: "N/A",
      crossBorder: "Not allowed",
    },
    openingHours: ["Mon–Sun 10:00–19:00"],
  },
  {
    slug: "morocco-yacht-life",
    name: "Morocco Yacht Life",
    city: "Tangier",
    category: "Boats",
    logo: "https://placehold.co/100x100.png",
    verified: true,
    languages: ["EN", "FR", "ES"],
    shortAbout: "Luxury yacht experiences and private charters in the Strait of Gibraltar.",
    longAbout: "Experience the height of luxury with Morocco Yacht Life. Our fleet of modern, fully-crewed yachts is available for private charter. Whether it's a day trip, a sunset cruise, or a special event, we provide an unparalleled level of service and comfort. See the coastlines of two continents from the deck of your private yacht.",
    policies: {
      deposit: "A charter deposit is required.",
      fuel: "Same-to-same",
      kilometers: "N/A",
      pickupDocs: "Booking confirmation and ID.",
      changes: "Contact MarHire support for charter modifications.",
      intercity: "N/A",
      crossBorder: "Not allowed",
    },
    openingHours: ["Available for charter 24/7"],
  },
  {
    slug: "tangier-day-trips",
    name: "Tangier Day Trips",
    city: "Tangier",
    category: "Activities",
    logo: "https://placehold.co/100x100.png",
    verified: true,
    languages: ["EN", "ES", "FR"],
    shortAbout: "Private day trips from Tangier to Chefchaouen, Asilah, and Tetouan.",
    longAbout: "Use Tangier as your base to explore the best of Northern Morocco. We offer private, comfortable day trips to the famous blue city of Chefchaouen, the artistic coastal town of Asilah, and the historic city of Tetouan. Our all-inclusive trips with a private driver mean you can relax and enjoy the journey.",
    policies: {
      deposit: "No deposit for day trips.",
      fuel: "Same-to-same",
      kilometers: "N/A",
      pickupDocs: "Booking voucher.",
      changes: "Contact MarHire support.",
      intercity: "N/A",
      crossBorder: "Not allowed",
    },
    openingHours: ["Tours depart daily at 09:00"],
  },
  {
    slug: "tangier-food-tour",
    name: "Tangier Food Tour",
    city: "Tangier",
    category: "Activities",
    logo: "https://placehold.co/100x100.png",
    verified: false,
    languages: ["EN", "FR"],
    shortAbout: "Explore the diverse culinary scene of Tangier with a guided walking food tour.",
    longAbout: "Taste the unique flavors of Tangier, a city influenced by Moroccan, Spanish, and French cuisines. Our walking tour takes you through the bustling souks and hidden alleyways to sample local specialties, from fresh seafood to delicious pastries. It's a journey for your taste buds.",
    policies: {
      deposit: "No deposit.",
      fuel: "Same-to-same",
      kilometers: "N/A",
      pickupDocs: "Booking confirmation.",
      changes: "Contact MarHire support.",
      intercity: "N/A",
      crossBorder: "Not allowed",
    },
    openingHours: ["Tours at 12:00 and 17:00"],
  },
  // Add other partners as needed to cover all listings
  {
    slug: "ciel-d-afrique-marrakech",
    name: "Ciel d'Afrique",
    city: "Marrakech",
    category: "Activities",
    logo: "https://placehold.co/100x100.png",
    verified: true,
    languages: ["EN", "FR"],
    shortAbout: "The original hot air balloon experience over the Atlas Mountains.",
    longAbout: "For over 30 years, Ciel d'Afrique has been offering breathtaking hot air balloon flights over the stunning landscapes near Marrakech. Witness a sunrise over the Atlas Mountains from a unique perspective. Our experience includes a traditional breakfast and a flight certificate.",
    policies: {
        deposit: "Full payment required at booking.",
        fuel: "Same-to-same",
        kilometers: "N/A",
        pickupDocs: "Booking confirmation.",
        changes: "Contact MarHire support. Weather-related cancellations are rescheduled or fully refunded.",
        intercity: "N/A",
        crossBorder: "Not allowed",
    },
    openingHours: ["Flights are at sunrise, daily"],
  },
    {
    slug: "la-maison-arabe-marrakech",
    name: "La Maison Arabe",
    city: "Marrakech",
    category: "Activities",
    logo: "https://placehold.co/100x100.png",
    verified: true,
    languages: ["EN", "FR"],
    shortAbout: "Learn the secrets of Moroccan cuisine in a legendary riad.",
    longAbout: "Join a cooking workshop at the world-renowned La Maison Arabe hotel. Learn to prepare classic Moroccan dishes like tagine and couscous from expert dadas (traditional Moroccan cooks). The workshops are hands-on and conclude with enjoying the meal you've prepared.",
    policies: {
        deposit: "No deposit.",
        fuel: "Same-to-same",
        kilometers: "N/A",
        pickupDocs: "Booking voucher.",
        changes: "Contact MarHire support. Free cancellation up to 48 hours before the class.",
        intercity: "N/A",
        crossBorder: "Not allowed",
    },
    openingHours: ["Workshops at 10:00 and 15:00"],
  },
];


export const MOCK_LISTINGS: Listing[] = [
  // Car Rentals
  {
    id: '1',
    name: 'Renault Clio',
    type: 'Car Rental',
    image: 'https://placehold.co/1200x800.png',
    provider: {
      name: 'Hertz',
      logo: 'https://placehold.co/40x40.png',
      isVerified: true,
    },
    location: {
      city: 'Marrakech',
      neighborhood: 'Gueliz',
    },
    specs: {
      seats: 5,
      transmission: 'Manual',
      fuelType: 'Petrol',
      hasAc: true,
      fuelPolicy: 'Full to Full',
      kmPolicy: 'Unlimited',
    },
    badges: {
      freeCancellation: true,
      noDeposit: true,
    },
    price: {
      perDay: 35,
    },
  },
  {
    id: '2',
    name: 'Dacia Duster',
    type: 'Car Rental',
    image: 'https://placehold.co/1200x800.png',
    provider: {
      name: 'Avis',
      logo: 'https://placehold.co/40x40.png',
      isVerified: true,
    },
    location: {
      city: 'Marrakech',
      neighborhood: 'Medina',
    },
    specs: {
      seats: 5,
      transmission: 'Manual',
      fuelType: 'Diesel',
      hasAc: true,
      fuelPolicy: 'Full to Full',
      kmPolicy: 'Unlimited',
    },
    badges: {
      freeCancellation: true,
    },
    price: {
      perDay: 40,
    },
  },
  {
    id: '4',
    name: 'Hyundai i10',
    type: 'Car Rental',
    image: 'https://placehold.co/1200x800.png',
    provider: {
      name: 'Sixt',
      logo: 'https://placehold.co/40x40.png',
      isVerified: true,
    },
    location: {
      city: 'Casablanca',
      neighborhood: 'Maarif',
    },
    specs: {
      seats: 4,
      transmission: 'Automatic',
      fuelType: 'Petrol',
      hasAc: true,
      fuelPolicy: 'Same to Same',
      kmPolicy: 'Limited',
    },
    badges: {
      freeCancellation: true,
    },
    price: {
      perDay: 30,
    },
  },
  {
    id: '5',
    name: 'Tesla Model 3',
    type: 'Car Rental',
    image: 'https://placehold.co/1200x800.png',
    provider: {
      name: 'Green Mobility',
      logo: 'https://placehold.co/40x40.png',
      isVerified: true,
    },
    location: {
      city: 'Tangier',
      neighborhood: 'City Center',
    },
    specs: {
      seats: 5,
      transmission: 'Automatic',
      fuelType: 'Electric',
      hasAc: true,
      fuelPolicy: 'Same to Same',
      kmPolicy: 'Unlimited',
    },
    badges: {
      freeCancellation: true,
    },
    price: {
      perDay: 85,
    },
  },
  {
    id: 'car-5',
    name: 'Volkswagen Golf',
    type: 'Car Rental',
    image: 'https://placehold.co/1200x800.png',
    provider: {
      name: 'Europcar',
      logo: 'https://placehold.co/40x40.png',
      isVerified: true,
    },
    location: {
      city: 'Agadir',
      neighborhood: 'Beachfront',
    },
    specs: {
      seats: 5,
      transmission: 'Automatic',
      fuelType: 'Petrol',
      hasAc: true,
      fuelPolicy: 'Full to Full',
      kmPolicy: 'Unlimited',
    },
    badges: {
      freeCancellation: true,
      noDeposit: true,
    },
    price: {
      perDay: 50,
    },
  },
  {
    id: 'car-6',
    name: 'Peugeot 208',
    type: 'Car Rental',
    image: 'https://placehold.co/1200x800.png',
    provider: {
      name: 'Budget',
      logo: 'https://placehold.co/40x40.png',
      isVerified: true,
    },
    location: {
      city: 'Fes',
      neighborhood: 'Ville Nouvelle',
    },
    specs: {
      seats: 5,
      transmission: 'Manual',
      fuelType: 'Diesel',
      hasAc: true,
      fuelPolicy: 'Same to Same',
      kmPolicy: 'Limited',
    },
    badges: {
      freeCancellation: true,
    },
    price: {
      perDay: 32,
    },
  },
  {
    id: 'car-7',
    name: 'Fiat 500',
    type: 'Car Rental',
    image: 'https://placehold.co/1200x800.png',
    provider: {
      name: 'Local Drive',
      logo: 'https://placehold.co/40x40.png',
      isVerified: true,
    },
    location: {
      city: 'Casablanca',
      neighborhood: 'Anfa',
    },
    specs: {
      seats: 4,
      transmission: 'Manual',
      fuelType: 'Petrol',
      hasAc: false,
      fuelPolicy: 'Full to Full',
      kmPolicy: 'Unlimited',
    },
    badges: {
      freeCancellation: true,
    },
    price: {
      perDay: 25,
    },
  },
  {
    id: 'car-8',
    name: 'BMW 3 Series',
    type: 'Car Rental',
    image: 'https://placehold.co/1200x800.png',
    provider: {
      name: 'Premium Rentals',
      logo: 'https://placehold.co/40x40.png',
      isVerified: true,
    },
    location: {
      city: 'Marrakech',
      neighborhood: 'Hivernage',
    },
    specs: {
      seats: 5,
      transmission: 'Automatic',
      fuelType: 'Hybrid',
      hasAc: true,
      fuelPolicy: 'Full to Full',
      kmPolicy: 'Unlimited',
    },
    badges: {
      freeCancellation: true,
    },
    price: {
      perDay: 95,
    },
  },
  {
    id: 'car-9',
    name: 'Jeep Wrangler',
    type: 'Car Rental',
    image: 'https://placehold.co/1200x800.png',
    provider: {
        name: '4x4 Morocco',
        logo: 'https://placehold.co/40x40.png',
        isVerified: true,
    },
    location: {
        city: 'Agadir',
        neighborhood: 'Mountain Road',
    },
    specs: {
        seats: 4,
        transmission: 'Automatic',
        fuelType: 'Petrol',
        hasAc: true,
        fuelPolicy: 'Full to Full',
        kmPolicy: 'Limited',
    },
    badges: {
        freeCancellation: true,
    },
    price: {
        perDay: 75,
    },
  },
  {
    id: 'car-10',
    name: 'Audi A3',
    type: 'Car Rental',
    image: 'https://placehold.co/1200x800.png',
    provider: {
        name: 'Prestige Cars',
        logo: 'https://placehold.co/40x40.png',
        isVerified: true,
    },
    location: {
        city: 'Casablanca',
        neighborhood: 'Corniche',
    },
    specs: {
        seats: 5,
        transmission: 'Automatic',
        fuelType: 'Petrol',
        hasAc: true,
        fuelPolicy: 'Full to Full',
        kmPolicy: 'Unlimited',
    },
    badges: {
        freeCancellation: true,
    },
    price: {
        perDay: 80,
    },
  },
  {
    id: 'car-11',
    name: 'Dacia Logan',
    type: 'Car Rental',
    image: 'https://placehold.co/1200x800.png',
    provider: {
        name: 'Fez Rent',
        logo: 'https://placehold.co/40x40.png',
        isVerified: true,
    },
    location: {
        city: 'Fes',
        neighborhood: 'Airport',
    },
    specs: {
        seats: 5,
        transmission: 'Manual',
        fuelType: 'Diesel',
        hasAc: true,
        fuelPolicy: 'Same to Same',
        kmPolicy: 'Unlimited',
    },
    badges: {
        freeCancellation: true,
        noDeposit: true,
    },
    price: {
        perDay: 28,
    },
  },
  {
    id: 'car-12',
    name: 'Kia Picanto',
    type: 'Car Rental',
    image: 'https://placehold.co/1200x800.png',
    provider: {
        name: 'Tangier Easy Rent',
        logo: 'https://placehold.co/40x40.png',
        isVerified: true,
    },
    location: {
        city: 'Tangier',
        neighborhood: 'Port',
    },
    specs: {
        seats: 4,
        transmission: 'Automatic',
        fuelType: 'Petrol',
        hasAc: true,
        fuelPolicy: 'Full to Full',
        kmPolicy: 'Limited',
    },
    badges: {
        freeCancellation: true,
    },
    price: {
        perDay: 29,
    },
  },
  // Private Drivers
  {
    id: '3',
    name: 'Mercedes V-Class',
    type: 'Private Driver',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
      name: 'Marrakech Premium',
      logo: 'https://placehold.co/40x40.png',
      isVerified: true,
    },
    location: {
      city: 'Marrakech',
      neighborhood: 'Airport Transfer',
    },
    specs: {
      seats: 7,
      luggage: 6,
      languages: ["EN", "FR", "AR"],
      hasAc: true,
    },
    badges: {
      freeCancellation: true,
    },
    price: {
      perDay: 0,
      perTrip: 120,
    },
  },
  {
    id: 'driver-2',
    name: 'Range Rover Vogue',
    type: 'Private Driver',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
      name: 'Casablanca VIP',
      logo: 'https://placehold.co/40x40.png',
      isVerified: true,
    },
    location: {
      city: 'Casablanca',
      neighborhood: 'City Tour',
    },
    specs: {
      seats: 4,
      luggage: 4,
      languages: ["EN", "FR"],
      hasAc: true,
    },
    badges: {
      freeCancellation: true,
    },
    price: {
      perDay: 0,
      perTrip: 200,
    },
  },
  {
    id: 'driver-3',
    name: 'Mercedes S-Class',
    type: 'Private Driver',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
      name: 'Fez Executive',
      logo: 'https://placehold.co/40x40.png',
      isVerified: true,
    },
    location: {
      city: 'Fes',
      neighborhood: 'Day Trip to Meknes',
    },
    specs: {
      seats: 4,
      luggage: 3,
      languages: ["FR", "AR"],
      hasAc: true,
    },
    badges: {
      freeCancellation: true,
    },
    price: {
      perDay: 0,
      perTrip: 180,
    },
  },
  {
    id: 'driver-4',
    name: 'Ford Tourneo',
    type: 'Private Driver',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
      name: 'Agadir Shuttle',
      logo: 'https://placehold.co/40x40.png',
      isVerified: true,
    },
    location: {
      city: 'Agadir',
      neighborhood: 'Group Excursion',
    },
    specs: {
      seats: 8,
      luggage: 8,
      languages: ["EN", "DE", "FR"],
      hasAc: true,
    },
    badges: {
      freeCancellation: true,
    },
    price: {
      perDay: 0,
      perTrip: 100,
    },
  },
  {
    id: 'driver-5',
    name: 'Toyota Land Cruiser',
    type: 'Private Driver',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
      name: 'Atlas Expeditions',
      logo: 'https://placehold.co/40x40.png',
      isVerified: true,
    },
    location: {
      city: 'Marrakech',
      neighborhood: 'Atlas Mountains Trip',
    },
    specs: {
      seats: 6,
      luggage: 5,
      languages: ["EN", "ES", "BER"],
      hasAc: true,
    },
    badges: {
      freeCancellation: true,
    },
    price: {
      perDay: 0,
      perTrip: 150,
    },
  },
  {
    id: 'driver-6',
    name: 'BMW 5 Series',
    type: 'Private Driver',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
      name: 'Tangier Connect',
      logo: 'https://placehold.co/40x40.png',
      isVerified: true,
    },
    location: {
      city: 'Tangier',
      neighborhood: 'Corporate Travel',
    },
    specs: {
      seats: 4,
      luggage: 3,
      languages: ["EN", "FR", "ES"],
      hasAc: true,
    },
    badges: {
      freeCancellation: true,
    },
    price: {
      perDay: 0,
      perTrip: 160,
    },
  },
  {
    id: 'driver-7',
    name: 'Skoda Octavia',
    type: 'Private Driver',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
      name: 'Morocco Direct',
      logo: 'https://placehold.co/40x40.png',
      isVerified: true,
    },
    location: {
      city: 'Casablanca',
      neighborhood: 'Inter-city Transfer',
    },
    specs: {
      seats: 4,
      luggage: 4,
      languages: ["AR"],
      hasAc: true,
    },
    badges: {
      freeCancellation: true,
    },
    price: {
      perDay: 0,
      perTrip: 90,
    },
  },
  {
    id: 'driver-8',
    name: 'Luxury Sprinter Van',
    type: 'Private Driver',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
      name: 'Group Travel Morocco',
      logo: 'https://placehold.co/40x40.png',
      isVerified: true,
    },
    location: {
      city: 'Marrakech',
      neighborhood: 'Multi-day Tour',
    },
    specs: {
      seats: 15,
      luggage: 15,
      languages: ["EN", "FR"],
      hasAc: true,
    },
    badges: {
      freeCancellation: true,
    },
    price: {
      perDay: 0,
      perTrip: 300,
    },
  },
  {
    id: 'driver-9',
    name: 'VW Touareg',
    type: 'Private Driver',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
        name: 'Essaouira Drives',
        logo: 'https://placehold.co/40x40.png',
        isVerified: true,
    },
    location: {
        city: 'Agadir',
        neighborhood: 'Coastal Tour',
    },
    specs: {
      seats: 4,
      luggage: 4,
      languages: ["EN", "FR"],
      hasAc: true,
    },
badges: {
        freeCancellation: true,
    },
    price: {
        perDay: 0,
        perTrip: 130,
    },
  },
  {
    id: 'driver-10',
    name: 'Mercedes C-Class',
    type: 'Private Driver',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
        name: 'Rabat Rides',
        logo: 'https://placehold.co/40x40.png',
        isVerified: true,
    },
    location: {
        city: 'Tangier',
        neighborhood: 'Business Meeting',
    },
    specs: {
      seats: 4,
      luggage: 3,
      languages: ["EN", "FR", "AR"],
      hasAc: true,
    },
    badges: {
        freeCancellation: true,
    },
    price: {
        perDay: 0,
        perTrip: 110,
    },
  },
  {
    id: 'driver-11',
    name: 'Renault Trafic',
    type: 'Private Driver',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
        name: 'Morocco Shuttle',
        logo: 'https://placehold.co/40x40.png',
        isVerified: true,
    },
    location: {
        city: 'Agadir',
        neighborhood: 'Airport Transfer',
    },
    specs: {
      seats: 9,
      luggage: 10,
      languages: ["FR", "AR"],
      hasAc: true,
    },
    badges: {
        freeCancellation: true,
    },
    price: {
        perDay: 0,
        perTrip: 80,
    },
  },
  {
    id: 'driver-12',
    name: 'Porsche Cayenne',
    type: 'Private Driver',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
        name: 'Marrakech Luxury',
        logo: 'https://placehold.co/40x40.png',
        isVerified: true,
    },
    location: {
        city: 'Marrakech',
        neighborhood: 'VIP Service',
    },
    specs: {
      seats: 4,
      luggage: 3,
      languages: ["EN", "FR", "RU"],
      hasAc: true,
    },
    badges: {
        freeCancellation: true,
    },
    price: {
        perDay: 0,
        perTrip: 250,
    },
  },
  // Boats
  {
    id: '6',
    name: 'Classic Yacht Tour',
    type: 'Boat',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
      name: 'Agadir Cruises',
      logo: 'https://placehold.co/40x40.png',
      isVerified: true,
    },
    location: {
      city: 'Agadir',
      neighborhood: 'Marina',
    },
    specs: {
      seats: 12,
      captain: "With Captain",
    },
    badges: {
       freeCancellation: true,
    },
    price: {
      perDay: 450,
      perHour: 60,
    },
  },
  {
    id: 'boat-2',
    name: 'Speedboat Adventure',
    type: 'Boat',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
      name: 'Tangier Water Sports',
      logo: 'https://placehold.co/40x40.png',
      isVerified: true,
    },
    location: {
      city: 'Tangier',
      neighborhood: 'Bay of Tangier',
    },
    specs: {
      seats: 6,
      captain: 'Without Captain',
    },
    badges: {
      freeCancellation: true,
    },
    price: {
      perDay: 250,
      perHour: 48,
    },
  },
  {
    id: 'boat-3',
    name: 'Catamaran Day Sail',
    type: 'Boat',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
      name: 'Essaouira Winds',
      logo: 'https://placehold.co/40x40.png',
      isVerified: true,
    },
    location: {
      city: 'Agadir',
      neighborhood: 'Coastal Cruise',
    },
    specs: {
      seats: 18,
      captain: 'With Captain',
    },
    badges: {
      freeCancellation: true,
    },
    price: {
      perDay: 600,
      perHour: 80,
    },
  },
  {
    id: 'boat-4',
    name: 'Jet Ski Rental',
    type: 'Boat',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
      name: 'Marrakech Lake Sports',
      logo: 'https://placehold.co/40x40.png',
      isVerified: true,
    },
    location: {
      city: 'Marrakech',
      neighborhood: 'Lalla Takerkoust Lake',
    },
    specs: {
      seats: 2,
      captain: 'Without Captain',
    },
    badges: {
      freeCancellation: true,
    },
    price: {
      perDay: 0,
      perHour: 80,
    },
  },
  {
    id: 'boat-5',
    name: 'Fishing Boat Charter',
    type: 'Boat',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
      name: 'Atlantic Fishing',
      logo: 'https://placehold.co/40x40.png',
      isVerified: true,
    },
    location: {
      city: 'Casablanca',
      neighborhood: 'Offshore',
    },
    specs: {
      seats: 8,
      captain: 'With Captain',
    },
    badges: {
      freeCancellation: true,
    },
    price: {
      perDay: 350,
      perHour: 50,
    },
  },
  {
    id: 'boat-6',
    name: 'Luxury Yacht Experience',
    type: 'Boat',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
      name: 'Morocco Yacht Life',
      logo: 'https://placehold.co/40x40.png',
      isVerified: true,
    },
    location: {
      city: 'Tangier',
      neighborhood: 'Strait of Gibraltar',
    },
    specs: {
      seats: 10,
      captain: 'With Captain',
    },
    badges: {
      freeCancellation: true,
    },
    price: {
      perDay: 1200,
      perHour: 150,
    },
  },
  {
    id: 'boat-7',
    name: 'Traditional Felucca Ride',
    type: 'Boat',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
      name: 'Local River Tours',
      logo: 'https://placehold.co/40x40.png',
      isVerified: true,
    },
    location: {
      city: 'Fes',
      neighborhood: 'Sebou River',
    },
    specs: {
      seats: 10,
      captain: 'With Captain',
    },
    badges: {
      freeCancellation: true,
    },
    price: {
      perDay: 50,
      perHour: 15,
    },
  },
  {
    id: 'boat-8',
    name: 'Party Boat Rental',
    type: 'Boat',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
      name: 'Agadir Party Boats',
      logo: 'https://placehold.co/40x40.png',
      isVerified: true,
    },
    location: {
      city: 'Agadir',
      neighborhood: 'Coastal Party Cruise',
    },
    specs: {
      seats: 25,
      captain: 'With Captain',
    },
    badges: {
      freeCancellation: true,
    },
    price: {
      perDay: 800,
      perHour: 120,
    },
  },
  {
    id: 'boat-9',
    name: 'RIB Boat Excursion',
    type: 'Boat',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
        name: 'Agadir Speedboat',
        logo: 'https://placehold.co/40x40.png',
        isVerified: true,
    },
    location: {
        city: 'Agadir',
        neighborhood: 'Taghazout Bay',
    },
    specs: {
        seats: 10,
        captain: 'With Captain',
    },
    badges: {
        freeCancellation: true,
    },
    price: {
        perDay: 300,
        perHour: 70,
    },
  },
  {
    id: 'boat-10',
    name: 'Pirate Ship Tour',
    type: 'Boat',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
        name: 'Essaouira Pirates',
        logo: 'https://placehold.co/40x40.png',
        isVerified: true,
    },
    location: {
        city: 'Agadir',
        neighborhood: 'Old Port',
    },
    specs: {
        seats: 30,
        captain: 'With Captain',
    },
    badges: {
        freeCancellation: true,
    },
    price: {
        perDay: 150,
        perHour: 25,
    },
  },
  {
    id: 'boat-11',
    name: 'Glass Bottom Boat',
    type: 'Boat',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
        name: 'Tangier Reef Explorer',
        logo: 'https://placehold.co/40x40.png',
        isVerified: true,
    },
    location: {
        city: 'Tangier',
        neighborhood: 'Coastal Waters',
    },
    specs: {
        seats: 15,
        captain: 'With Captain',
    },
    badges: {
        freeCancellation: true,
    },
    price: {
        perDay: 200,
        perHour: 35,
    },
  },
  {
    id: 'boat-12',
    name: 'Sailing Dinghy Rental',
    type: 'Boat',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
        name: 'Dakhla Wind Sports',
        logo: 'https://placehold.co/40x40.png',
        isVerified: true,
    },
    location: {
        city: 'Casablanca',
        neighborhood: 'Dakhla Lagoon',
    },
    specs: {
        seats: 2,
        captain: 'Without Captain',
    },
    badges: {
        freeCancellation: true,
    },
    price: {
        perDay: 100,
        perHour: 20,
    },
  },
  // Activities
  {
    id: 'activity-1',
    name: 'Marrakech Medina Walking Tour',
    type: 'Activity',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
      name: 'Marrakech Guided Tours',
      logo: 'https://placehold.co/40x40.png',
      isVerified: true,
    },
    location: {
      city: 'Marrakech',
      neighborhood: 'Old Medina',
    },
    specs: {
        activityType: 'Group',
        difficulty: 'Easy',
    },
    badges: {
      freeCancellation: true,
    },
    price: {
      perDay: 40,
    },
  },
  {
    id: 'activity-2',
    name: 'Atlas Mountains Hot Air Balloon',
    type: 'Activity',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
      name: 'Ciel d\'Afrique',
      logo: 'https://placehold.co/40x40.png',
      isVerified: true,
    },
    location: {
      city: 'Marrakech',
      neighborhood: 'Atlas Mountains',
    },
    specs: {
        activityType: 'Group',
        difficulty: 'Easy',
    },
    badges: {
      freeCancellation: true,
    },
    price: {
      perDay: 205,
    },
  },
  {
    id: 'activity-3',
    name: 'Fez Tannery Visit & Leather Workshop',
    type: 'Activity',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
      name: 'Fez Artisanal Tours',
      logo: 'https://placehold.co/40x40.png',
      isVerified: true,
    },
    location: {
      city: 'Fes',
      neighborhood: 'Old Medina',
    },
    specs: {
        activityType: 'Private',
        difficulty: 'Medium',
    },
    badges: {
      freeCancellation: true,
    },
    price: {
      perDay: 60,
    },
  },
  {
    id: 'activity-4',
    name: 'Quad Biking in Agafay Desert',
    type: 'Activity',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
      name: 'Agafay Desert Adventures',
      logo: 'https://placehold.co/40x40.png',
      isVerified: true,
    },
    location: {
      city: 'Marrakech',
      neighborhood: 'Agafay Desert',
    },
    specs: {
        activityType: 'Group',
        difficulty: 'Medium',
    },
    badges: {
      freeCancellation: true,
    },
    price: {
      perDay: 75,
    },
  },
  {
    id: 'activity-5',
    name: 'Moroccan Cooking Class',
    type: 'Activity',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
      name: 'La Maison Arabe',
      logo: 'https://placehold.co/40x40.png',
      isVerified: true,
    },
    location: {
      city: 'Marrakech',
      neighborhood: 'Bab Doukkala',
    },
    specs: {
        activityType: 'Group',
        difficulty: 'Easy',
    },
    badges: {
      freeCancellation: true,
    },
    price: {
      perDay: 65,
    },
  },
  {
    id: 'activity-6',
    name: 'Surfing Lessons in Taghazout',
    type: 'Activity',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
      name: 'Surf Berbere',
      logo: 'https://placehold.co/40x40.png',
      isVerified: true,
    },
    location: {
      city: 'Agadir',
      neighborhood: 'Taghazout',
    },
    specs: {
        activityType: 'Group',
        difficulty: 'Medium',
    },
    badges: {
      freeCancellation: true,
    },
    price: {
      perDay: 50,
    },
  },
  {
    id: 'activity-7',
    name: 'Chefchaouen "Blue City" Tour',
    type: 'Activity',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
      name: 'Tangier Day Trips',
      logo: 'https://placehold.co/40x40.png',
      isVerified: true,
    },
    location: {
      city: 'Tangier',
      neighborhood: 'Day Trip',
    },
    specs: {
        activityType: 'Private',
        difficulty: 'Easy',
    },
    badges: {
      freeCancellation: true,
    },
    price: {
      perDay: 110,
    },
  },
  {
    id: 'activity-8',
    name: 'Camel Ride at Sunset',
    type: 'Activity',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
      name: 'Palmerie Camels',
      logo: 'https://placehold.co/40x40.png',
      isVerified: true,
    },
    location: {
      city: 'Marrakech',
      neighborhood: 'Palmerie',
    },
    specs: {
        activityType: 'Group',
        difficulty: 'Easy',
    },
    badges: {
      freeCancellation: true,
    },
    price: {
      perDay: 45,
    },
  },
  {
    id: 'activity-9',
    name: 'Hassan II Mosque Tour',
    type: 'Activity',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
        name: 'Casablanca City Tours',
        logo: 'https://placehold.co/40x40.png',
        isVerified: true,
    },
    location: {
        city: 'Casablanca',
        neighborhood: 'Boulevard de la Corniche',
    },
    specs: {
        activityType: 'Group',
        difficulty: 'Easy',
    },
    badges: {
        freeCancellation: true,
    },
    price: {
        perDay: 15,
    },
  },
  {
    id: 'activity-10',
    name: 'Ouzoud Waterfalls Day Trip',
    type: 'Activity',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
        name: 'Atlas Excursions',
        logo: 'https://placehold.co/40x40.png',
        isVerified: true,
    },
    location: {
        city: 'Marrakech',
        neighborhood: 'Day trip from Marrakech',
    },
    specs: {
        activityType: 'Group',
        difficulty: 'Medium',
    },
    badges: {
        freeCancellation: true,
    },
    price: {
        perDay: 30,
    },
  },
  {
    id: 'activity-11',
    name: 'Sahara Desert Camping',
    type: 'Activity',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
        name: 'Desert Dreams',
        logo: 'https://placehold.co/40x40.png',
        isVerified: true,
    },
    location: {
        city: 'Fes',
        neighborhood: 'Merzouga',
    },
    specs: {
        activityType: 'Private',
        difficulty: 'Hard',
    },
    badges: {
        freeCancellation: true,
    },
    price: {
        perDay: 150,
    },
  },
  {
    id: 'activity-12',
    name: 'Jardin Majorelle Visit',
    type: 'Activity',
    image: 'https://placehold.co/1200x800.png',
    gallery: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    provider: {
        name: 'Marrakech Tickets',
        logo: 'https://placehold.co/40x40.png',
        isVerified: true,
    },
    location: {
        city: 'Marrakech',
        neighborhood: 'Gueliz',
    },
    specs: {
        activityType: 'Private',
        difficulty: 'Easy',
    },
    badges: {
        freeCancellation: true,
    },
    price: {
        perDay: 15,
    },
  },
];
const carRentals = [
  // Agadir
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `car-agadir-${i + 1}`,
    name: `Agadir Car ${i + 1}`,
    type: 'Car Rental' as const,
    image: 'https://placehold.co/1200x800.png',
    provider: { name: `Agadir Rent ${i + 1}`, logo: 'https://placehold.co/40x40.png', isVerified: true },
    location: { city: 'Agadir', neighborhood: 'City Center' },
    specs: { seats: 5, transmission: 'Automatic' as const, fuelType: 'Petrol' as const, hasAc: true, fuelPolicy: 'Full to Full' as const, kmPolicy: 'Unlimited' as const },
    badges: { freeCancellation: true, noDeposit: i % 2 === 0 },
    price: { perDay: 30 + i * 5 },
  })),
  // Marrakech
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `car-marrakech-${i + 1}`,
    name: `Marrakech Car ${i + 1}`,
    type: 'Car Rental' as const,
    image: 'https://placehold.co/1200x800.png',
    provider: { name: `Marrakech Wheels ${i + 1}`, logo: 'https://placehold.co/40x40.png', isVerified: true },
    location: { city: 'Marrakech', neighborhood: 'Gueliz' },
    specs: { seats: 5, transmission: 'Manual' as const, fuelType: 'Diesel' as const, hasAc: true, fuelPolicy: 'Same to Same' as const, kmPolicy: 'Limited' as const },
    badges: { freeCancellation: true, noDeposit: i % 2 !== 0 },
    price: { perDay: 28 + i * 5 },
  })),
  // Casablanca
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `car-casablanca-${i + 1}`,
    name: `Casablanca Car ${i + 1}`,
    type: 'Car Rental' as const,
    image: 'https://placehold.co/1200x800.png',
    provider: { name: `Casa Drives ${i + 1}`, logo: 'https://placehold.co/40x40.png', isVerified: true },
    location: { city: 'Casablanca', neighborhood: 'Maarif' },
    specs: { seats: 4, transmission: 'Automatic' as const, fuelType: 'Hybrid' as const, hasAc: true, fuelPolicy: 'Full to Full' as const, kmPolicy: 'Unlimited' as const },
    badges: { freeCancellation: true, noDeposit: i % 2 === 0 },
    price: { perDay: 40 + i * 5 },
  })),
  // Fes
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `car-fes-${i + 1}`,
    name: `Fes Car ${i + 1}`,
    type: 'Car Rental' as const,
    image: 'https://placehold.co/1200x800.png',
    provider: { name: `Fes Rentals ${i + 1}`, logo: 'https://placehold.co/40x40.png', isVerified: true },
    location: { city: 'Fes', neighborhood: 'Ville Nouvelle' },
    specs: { seats: 5, transmission: 'Manual' as const, fuelType: 'Petrol' as const, hasAc: true, fuelPolicy: 'Full to Full' as const, kmPolicy: 'Unlimited' as const },
    badges: { freeCancellation: true, noDeposit: i % 2 !== 0 },
    price: { perDay: 33 + i * 4 },
  })),
  // Tangier
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `car-tangier-${i + 1}`,
    name: `Tangier Car ${i + 1}`,
    type: 'Car Rental' as const,
    image: 'https://placehold.co/1200x800.png',
    provider: { name: `Tangier Motors ${i + 1}`, logo: 'https://placehold.co/40x40.png', isVerified: true },
    location: { city: 'Tangier', neighborhood: 'Port' },
    specs: { seats: 5, transmission: 'Automatic' as const, fuelType: 'Diesel' as const, hasAc: true, fuelPolicy: 'Same to Same' as const, kmPolicy: 'Unlimited' as const },
    badges: { freeCancellation: true, noDeposit: i % 2 === 0 },
    price: { perDay: 35 + i * 5 },
  })),
  // Essaouira
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `car-essaouira-${i + 1}`,
    name: `Essaouira Car ${i + 1}`,
    type: 'Car Rental' as const,
    image: 'https://placehold.co/1200x800.png',
    provider: { name: `Essaouira Rides ${i + 1}`, logo: 'https://placehold.co/40x40.png', isVerified: true },
    location: { city: 'Essaouira', neighborhood: 'Medina' },
    specs: { seats: 4, transmission: 'Manual' as const, fuelType: 'Petrol' as const, hasAc: false, fuelPolicy: 'Full to Full' as const, kmPolicy: 'Limited' as const },
    badges: { freeCancellation: true, noDeposit: i % 2 !== 0 },
    price: { perDay: 25 + i * 3 },
  })),
  // Rabat
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `car-rabat-${i + 1}`,
    name: `Rabat Car ${i + 1}`,
    type: 'Car Rental' as const,
    image: 'https://placehold.co/1200x800.png',
    provider: { name: `Rabat Auto ${i + 1}`, logo: 'https://placehold.co/40x40.png', isVerified: true },
    location: { city: 'Rabat', neighborhood: 'Agdal' },
    specs: { seats: 5, transmission: 'Automatic' as const, fuelType: 'Petrol' as const, hasAc: true, fuelPolicy: 'Full to Full' as const, kmPolicy: 'Unlimited' as const },
    badges: { freeCancellation: true, noDeposit: i % 2 === 0 },
    price: { perDay: 38 + i * 5 },
  })),
];

const boatRentals = [
  // Agadir
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `boat-agadir-${i + 1}`,
    name: `Agadir Boat Trip ${i + 1}`,
    type: 'Boat' as const,
    image: 'https://placehold.co/1200x800.png',
    provider: { name: `Agadir Yachting ${i + 1}`, logo: 'https://placehold.co/40x40.png', isVerified: true },
    location: { city: 'Agadir', neighborhood: 'Marina' },
    specs: { seats: 10 + i, captain: i % 2 === 0 ? 'With Captain' as const : 'Without Captain' as const },
    badges: { freeCancellation: true },
    price: { perDay: 300 + i * 50, perHour: 50 + i * 10 },
  })),
  // Marrakech (Lalla Takerkoust Lake)
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `boat-marrakech-${i + 1}`,
    name: `Lake Jet Ski ${i + 1}`,
    type: 'Boat' as const,
    image: 'https://placehold.co/1200x800.png',
    provider: { name: `Atlas Lake Sports ${i + 1}`, logo: 'https://placehold.co/40x40.png', isVerified: true },
    location: { city: 'Marrakech', neighborhood: 'Lalla Takerkoust' },
    specs: { seats: 2, captain: 'Without Captain' as const },
    badges: { freeCancellation: true },
    price: { perDay: 200 + i * 20, perHour: 40 + i * 5 },
  })),
  // Casablanca
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `boat-casablanca-${i + 1}`,
    name: `Casablanca Fishing Charter ${i + 1}`,
    type: 'Boat' as const,
    image: 'https://placehold.co/1200x800.png',
    provider: { name: `Casa Nautic ${i + 1}`, logo: 'https://placehold.co/40x40.png', isVerified: true },
    location: { city: 'Casablanca', neighborhood: 'Port' },
    specs: { seats: 6 + i, captain: 'With Captain' as const },
    badges: { freeCancellation: true },
    price: { perDay: 400 + i * 50, perHour: 60 + i * 10 },
  })),
  // Fes (No direct water access, theoretical)
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `boat-fes-${i + 1}`,
    name: `River Tour ${i + 1}`,
    type: 'Boat' as const,
    image: 'https://placehold.co/1200x800.png',
    provider: { name: `Fes River Tours ${i + 1}`, logo: 'https://placehold.co/40x40.png', isVerified: true },
    location: { city: 'Fes', neighborhood: 'Sebou River' },
    specs: { seats: 8, captain: 'With Captain' as const },
    badges: { freeCancellation: true },
    price: { perDay: 100 + i * 10, perHour: 20 + i * 2 },
  })),
  // Tangier
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `boat-tangier-${i + 1}`,
    name: `Tangier Strait Crossing ${i + 1}`,
    type: 'Boat' as const,
    image: 'https://placehold.co/1200x800.png',
    provider: { name: `Strait Liners ${i + 1}`, logo: 'https://placehold.co/40x40.png', isVerified: true },
    location: { city: 'Tangier', neighborhood: 'Port de Tanger Med' },
    specs: { seats: 12 + i, captain: 'With Captain' as const },
    badges: { freeCancellation: true },
    price: { perDay: 500 + i * 60, perHour: 90 + i * 10 },
  })),
  // Essaouira
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `boat-essaouira-${i + 1}`,
    name: `Essaouira Sailing Trip ${i + 1}`,
    type: 'Boat' as const,
    image: 'https://placehold.co/1200x800.png',
    provider: { name: `Wind City Sails ${i + 1}`, logo: 'https://placehold.co/40x40.png', isVerified: true },
    location: { city: 'Essaouira', neighborhood: 'Old Port' },
    specs: { seats: 8 + i, captain: 'With Captain' as const },
    badges: { freeCancellation: true },
    price: { perDay: 250 + i * 30, perHour: 45 + i * 5 },
  })),
  // Rabat
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `boat-rabat-${i + 1}`,
    name: `Rabat River Cruise ${i + 1}`,
    type: 'Boat' as const,
    image: 'https://placehold.co/1200x800.png',
    provider: { name: `Rabat Yachts ${i + 1}`, logo: 'https://placehold.co/40x40.png', isVerified: true },
    location: { city: 'Rabat', neighborhood: 'Bouregreg Marina' },
    specs: { seats: 15, captain: 'With Captain' as const },
    badges: { freeCancellation: true },
    price: { perDay: 350 + i * 40, perHour: 55 + i * 10 },
  })),
];

const privateDrivers = [
  // Agadir
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `driver-agadir-${i + 1}`,
    name: `Agadir Driver Service ${i + 1}`,
    type: 'Private Driver' as const,
    image: 'https://placehold.co/1200x800.png',
    provider: { name: `Agadir Transfers ${i + 1}`, logo: 'https://placehold.co/40x40.png', isVerified: true },
    location: { city: 'Agadir', neighborhood: 'Airport Transfer' },
    specs: { seats: 4 + (i % 3), luggage: 4 + (i % 3), languages: ['EN', 'FR'], hasAc: true },
    badges: { freeCancellation: true },
    price: { perDay: 0, perTrip: 100 + i * 10 },
  })),
  // Marrakech
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `driver-marrakech-${i + 1}`,
    name: `Marrakech Chauffeur ${i + 1}`,
    type: 'Private Driver' as const,
    image: 'https://placehold.co/1200x800.png',
    provider: { name: `Marrakech VIP ${i + 1}`, logo: 'https://placehold.co/40x40.png', isVerified: true },
    location: { city: 'Marrakech', neighborhood: 'City Tours' },
    specs: { seats: 7, luggage: 6, languages: ['EN', 'FR', 'AR'], hasAc: true },
    badges: { freeCancellation: true },
    price: { perDay: 0, perTrip: 120 + i * 15 },
  })),
  // Casablanca
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `driver-casablanca-${i + 1}`,
    name: `Casablanca Executive ${i + 1}`,
    type: 'Private Driver' as const,
    image: 'https://placehold.co/1200x800.png',
    provider: { name: `Casa Executive ${i + 1}`, logo: 'https://placehold.co/40x40.png', isVerified: true },
    location: { city: 'Casablanca', neighborhood: 'Business Travel' },
    specs: { seats: 4, luggage: 3, languages: ['FR', 'AR'], hasAc: true },
    badges: { freeCancellation: true },
    price: { perDay: 0, perTrip: 150 + i * 20 },
  })),
  // Fes
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `driver-fes-${i + 1}`,
    name: `Fes Guided Driver ${i + 1}`,
    type: 'Private Driver' as const,
    image: 'https://placehold.co/1200x800.png',
    provider: { name: `Fes City Guide ${i + 1}`, logo: 'https://placehold.co/40x40.png', isVerified: true },
    location: { city: 'Fes', neighborhood: 'Medina Exploration' },
    specs: { seats: 5, luggage: 4, languages: ['EN', 'FR', 'ES'], hasAc: true },
    badges: { freeCancellation: true },
    price: { perDay: 0, perTrip: 110 + i * 10 },
  })),
  // Tangier
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `driver-tangier-${i + 1}`,
    name: `Tangier Connect ${i + 1}`,
    type: 'Private Driver' as const,
    image: 'https://placehold.co/1200x800.png',
    provider: { name: `Tangier Professional ${i + 1}`, logo: 'https://placehold.co/40x40.png', isVerified: true },
    location: { city: 'Tangier', neighborhood: 'Inter-city' },
    specs: { seats: 4, luggage: 4, languages: ['EN', 'ES', 'FR'], hasAc: true },
    badges: { freeCancellation: true },
    price: { perDay: 0, perTrip: 130 + i * 10 },
  })),
  // Essaouira
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `driver-essaouira-${i + 1}`,
    name: `Essaouira Coastal Driver ${i + 1}`,
    type: 'Private Driver' as const,
    image: 'https://placehold.co/1200x800.png',
    provider: { name: `Windy City Drives ${i + 1}`, logo: 'https://placehold.co/40x40.png', isVerified: true },
    location: { city: 'Essaouira', neighborhood: 'Coastal Tours' },
    specs: { seats: 6, luggage: 5, languages: ['FR', 'EN'], hasAc: true },
    badges: { freeCancellation: true },
    price: { perDay: 0, perTrip: 90 + i * 10 },
  })),
  // Rabat
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `driver-rabat-${i + 1}`,
    name: `Rabat Diplomatic Service ${i + 1}`,
    type: 'Private Driver' as const,
    image: 'https://placehold.co/1200x800.png',
    provider: { name: `Rabat Official ${i + 1}`, logo: 'https://placehold.co/40x40.png', isVerified: true },
    location: { city: 'Rabat', neighborhood: 'Official Visits' },
    specs: { seats: 4, luggage: 3, languages: ['AR', 'FR', 'EN'], hasAc: true },
    badges: { freeCancellation: true },
    price: { perDay: 0, perTrip: 160 + i * 15 },
  })),
];

const activities = [
  // Agadir
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `activity-agadir-${i + 1}`,
    name: `Agadir Activity ${i + 1}`,
    type: 'Activity' as const,
    image: 'https://placehold.co/1200x800.png',
    provider: { name: `Agadir Adventures`, logo: 'https://placehold.co/40x40.png', isVerified: true },
    location: { city: 'Agadir', neighborhood: 'Taghazout' },
    specs: { activityType: 'Group' as const, difficulty: i % 3 === 0 ? 'Easy' as const : (i % 3 === 1 ? 'Medium' as const : 'Hard' as const) },
    badges: { freeCancellation: true },
    price: { perDay: 40 + i * 10 },
  })),
  // Marrakech
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `activity-marrakech-${i + 1}`,
    name: `Marrakech Experience ${i + 1}`,
    type: 'Activity' as const,
    image: 'https://placehold.co/1200x800.png',
    provider: { name: `Marrakech Wonders`, logo: 'https://placehold.co/40x40.png', isVerified: true },
    location: { city: 'Marrakech', neighborhood: 'Palmerie' },
    specs: { activityType: 'Private' as const, difficulty: 'Easy' as const },
    badges: { freeCancellation: true },
    price: { perDay: 50 + i * 15 },
  })),
  // Casablanca
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `activity-casablanca-${i + 1}`,
    name: `Casablanca Tour ${i + 1}`,
    type: 'Activity' as const,
    image: 'https://placehold.co/1200x800.png',
    provider: { name: `Casa Tours`, logo: 'https://placehold.co/40x40.png', isVerified: true },
    location: { city: 'Casablanca', neighborhood: 'Old Medina' },
    specs: { activityType: 'Group' as const, difficulty: 'Easy' as const },
    badges: { freeCancellation: true },
    price: { perDay: 30 + i * 5 },
  })),
  // Fes
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `activity-fes-${i + 1}`,
    name: `Fes Craft Workshop ${i + 1}`,
    type: 'Activity' as const,
    image: 'https://placehold.co/1200x800.png',
    provider: { name: `Fes Artisans`, logo: 'https://placehold.co/40x40.png', isVerified: true },
    location: { city: 'Fes', neighborhood: 'Medina' },
    specs: { activityType: 'Private' as const, difficulty: 'Medium' as const },
    badges: { freeCancellation: true },
    price: { perDay: 60 + i * 10 },
  })),
  // Tangier
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `activity-tangier-${i + 1}`,
    name: `Tangier History Walk ${i + 1}`,
    type: 'Activity' as const,
    image: 'https://placehold.co/1200x800.png',
    provider: { name: `Tangier Historic`, logo: 'https://placehold.co/40x40.png', isVerified: true },
    location: { city: 'Tangier', neighborhood: 'Kasbah' },
    specs: { activityType: 'Group' as const, difficulty: 'Easy' as const },
    badges: { freeCancellation: true },
    price: { perDay: 35 + i * 5 },
  })),
  // Essaouira
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `activity-essaouira-${i + 1}`,
    name: `Essaouira Art Tour ${i + 1}`,
    type: 'Activity' as const,
    image: 'https://placehold.co/1200x800.png',
    provider: { name: `Essaouira Arts`, logo: 'https://placehold.co/40x40.png', isVerified: true },
    location: { city: 'Essaouira', neighborhood: 'Art Galleries' },
    specs: { activityType: 'Private' as const, difficulty: 'Easy' as const },
    badges: { freeCancellation: true },
    price: { perDay: 45 + i * 5 },
  })),
  // Rabat
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `activity-rabat-${i + 1}`,
    name: `Rabat Monument Tour ${i + 1}`,
    type: 'Activity' as const,
    image: 'https://placehold.co/1200x800.png',
    provider: { name: `Rabat Heritage`, logo: 'https://placehold.co/40x40.png', isVerified: true },
    location: { city: 'Rabat', neighborhood: 'Historical Sites' },
    specs: { activityType: 'Group' as const, difficulty: 'Easy' as const },
    badges: { freeCancellation: true },
    price: { perDay: 40 + i * 5 },
  })),
];

MOCK_LISTINGS.push(...carRentals, ...boatRentals, ...privateDrivers, ...activities);

const additionalPartners: Partner[] = [
  {
    slug: "agadir-adventures",
    name: "Agadir Adventures",
    city: "Agadir",
    category: "Activities",
    logo: "https://placehold.co/100x100.png",
    verified: true,
    languages: ["EN", "FR", "DE"],
    shortAbout: "The best outdoor activities in the Agadir region, from Paradise Valley to sandboarding.",
    longAbout: "Agadir Adventures is your go-to for exploring the incredible nature surrounding Agadir. We offer guided tours to Paradise Valley, sandboarding on the coastal dunes, and much more. Our guides are local experts passionate about sharing the beauty of their region. All our tours include hotel pickup and are designed to be safe and fun for everyone.",
    policies: {
      deposit: "No deposit required for day trips.",
      fuel: "Same-to-same",
      kilometers: "N/A",
      pickupDocs: "Booking confirmation.",
      changes: "Contact MarHire support. Free cancellation is available.",
      intercity: "N/A",
      crossBorder: "Not allowed",
    },
    openingHours: ["Mon-Sun 08:30-18:30"],
  },
  {
    slug: "marrakech-wonders",
    name: "Marrakech Wonders",
    city: "Marrakech",
    category: "Activities",
    logo: "https://placehold.co/100x100.png",
    verified: true,
    languages: ["EN", "FR"],
    shortAbout: "Curated experiences in Marrakech, from camel rides in the Palmeraie to private city tours.",
    longAbout: "Marrakech Wonders offers a selection of the best experiences the Red City has to offer. Whether you want a magical sunset camel ride in the Palmeraie or an insightful private tour of the medina's hidden gems, our professional guides are here to make your trip unforgettable. We focus on quality, authenticity, and creating lasting memories.",
    policies: {
      deposit: "No deposit required.",
      fuel: "Same-to-same",
      kilometers: "N/A",
      pickupDocs: "Booking voucher.",
      changes: "Contact MarHire support.",
      intercity: "N/A",
      crossBorder: "Not allowed",
    },
    openingHours: ["Mon-Sun 09:00-20:00"],
  },
  {
    slug: "casa-tours",
    name: "Casa Tours",
    city: "Casablanca",
    category: "Activities",
    logo: "https://placehold.co/100x100.png",
    verified: true,
    languages: ["EN", "FR", "AR"],
    shortAbout: "In-depth guided tours of Casablanca's architectural and cultural highlights.",
    longAbout: "Explore the multifaceted identity of Casablanca with Casa Tours. Our expert guides will lead you through the city's famous Art Deco district, the bustling central market, and the magnificent Hassan II Mosque. We offer both group and private tours to provide a comprehensive look at Morocco's economic powerhouse.",
    policies: {
      deposit: "No deposit required.",
      fuel: "Same-to-same",
      kilometers: "N/A",
      pickupDocs: "Booking confirmation.",
      changes: "Contact MarHire support.",
      intercity: "N/A",
      crossBorder: "Not allowed",
    },
    openingHours: ["Tours run daily at 10:00 and 14:00"],
  },
  {
    slug: "fes-artisans",
    name: "Fes Artisans",
    city: "Fes",
    category: "Activities",
    logo: "https://placehold.co/100x100.png",
    verified: true,
    languages: ["EN", "FR", "ES"],
    shortAbout: "Authentic workshops and tours focused on the traditional crafts of Fes.",
    longAbout: "Immerse yourself in the ancient traditions of Fes with Fes Artisans. We offer unique workshops where you can try your hand at pottery or leatherwork, as well as guided tours that introduce you to the master craftsmen of the medina. It's a hands-on way to appreciate the city's incredible heritage.",
    policies: {
      deposit: "A small deposit is required for workshop bookings.",
      fuel: "Same-to-same",
      kilometers: "N/A",
      pickupDocs: "Booking voucher.",
      changes: "Contact MarHire support.",
      intercity: "N/A",
      crossBorder: "Not allowed",
    },
    openingHours: ["Mon-Sat 09:00-17:00"],
  },
  {
    slug: "tangier-historic",
    name: "Tangier Historic",
    city: "Tangier",
    category: "Activities",
    logo: "https://placehold.co/100x100.png",
    verified: true,
    languages: ["EN", "ES", "FR"],
    shortAbout: "Engaging historical walking tours through the Kasbah and medina of Tangier.",
    longAbout: "Walk through centuries of history with Tangier Historic. Our licensed guides are passionate storytellers who bring the city's fascinating past to life. Explore the legendary Kasbah, the bustling medina, and the places that inspired famous writers and artists. Our tours are the perfect introduction to this captivating city.",
    policies: {
      deposit: "No deposit required.",
      fuel: "Same-to-same",
      kilometers: "N/A",
      pickupDocs: "Booking confirmation.",
      changes: "Contact MarHire support. Free cancellation up to 24 hours in advance.",
      intercity: "N/A",
      crossBorder: "Not allowed",
    },
    openingHours: ["Tours run daily at 10:00 AM"],
  }
];

MOCK_PARTNERS.push(...additionalPartners);
