// Lightweight countries utility that generates localized country names
// using Intl.DisplayNames at runtime to avoid bundling large static lists.

// ISO 3166-1 alpha-2 region codes (including some territories commonly used in forms)
// Source baseline: CLDR/ISO. Kept as codes to minimize bundle size.
export const countryCodes = [
    "AF",
    "AX",
    "AL",
    "DZ",
    "AS",
    "AD",
    "AO",
    "AI",
    "AQ",
    "AG",
    "AR",
    "AM",
    "AW",
    "AU",
    "AT",
    "AZ",
    "BS",
    "BH",
    "BD",
    "BB",
    "BY",
    "BE",
    "BZ",
    "BJ",
    "BM",
    "BT",
    "BO",
    "BQ",
    "BA",
    "BW",
    "BV",
    "BR",
    "IO",
    "BN",
    "BG",
    "BF",
    "BI",
    "CV",
    "KH",
    "CM",
    "CA",
    "KY",
    "CF",
    "TD",
    "CL",
    "CN",
    "CX",
    "CC",
    "CO",
    "KM",
    "CG",
    "CD",
    "CK",
    "CR",
    "CI",
    "HR",
    "CU",
    "CW",
    "CY",
    "CZ",
    "DK",
    "DJ",
    "DM",
    "DO",
    "EC",
    "EG",
    "SV",
    "GQ",
    "ER",
    "EE",
    "SZ",
    "ET",
    "FK",
    "FO",
    "FJ",
    "FI",
    "FR",
    "GF",
    "PF",
    "TF",
    "GA",
    "GM",
    "GE",
    "DE",
    "GH",
    "GI",
    "GR",
    "GL",
    "GD",
    "GP",
    "GU",
    "GT",
    "GG",
    "GN",
    "GW",
    "GY",
    "HT",
    "HM",
    "VA",
    "HN",
    "HK",
    "HU",
    "IS",
    "IN",
    "ID",
    "IR",
    "IQ",
    "IE",
    "IM",
    "IL",
    "IT",
    "JM",
    "JP",
    "JE",
    "JO",
    "KZ",
    "KE",
    "KI",
    "KP",
    "KR",
    "KW",
    "KG",
    "LA",
    "LV",
    "LB",
    "LS",
    "LR",
    "LY",
    "LI",
    "LT",
    "LU",
    "MO",
    "MG",
    "MW",
    "MY",
    "MV",
    "ML",
    "MT",
    "MH",
    "MQ",
    "MR",
    "MU",
    "YT",
    "MX",
    "FM",
    "MD",
    "MC",
    "MN",
    "ME",
    "MS",
    "MA",
    "MZ",
    "MM",
    "NA",
    "NR",
    "NP",
    "NL",
    "NC",
    "NZ",
    "NI",
    "NE",
    "NG",
    "NU",
    "NF",
    "MK",
    "MP",
    "NO",
    "OM",
    "PK",
    "PW",
    "PS",
    "PA",
    "PG",
    "PY",
    "PE",
    "PH",
    "PN",
    "PL",
    "PT",
    "PR",
    "QA",
    "RE",
    "RO",
    "RU",
    "RW",
    "BL",
    "SH",
    "KN",
    "LC",
    "MF",
    "PM",
    "VC",
    "WS",
    "SM",
    "ST",
    "SA",
    "SN",
    "RS",
    "SC",
    "SL",
    "SG",
    "SX",
    "SK",
    "SI",
    "SB",
    "SO",
    "ZA",
    "GS",
    "SS",
    "ES",
    "LK",
    "SD",
    "SR",
    "SJ",
    "SE",
    "CH",
    "SY",
    "TW",
    "TJ",
    "TZ",
    "TH",
    "TL",
    "TG",
    "TK",
    "TO",
    "TT",
    "TN",
    "TR",
    "TM",
    "TC",
    "TV",
    "UG",
    "UA",
    "AE",
    "GB",
    "US",
    "UM",
    "UY",
    "UZ",
    "VU",
    "VE",
    "VN",
    "VG",
    "VI",
    "WF",
    "EH",
    "YE",
    "ZM",
    "ZW",
    "XK",
];

/**
 * Returns an array of { code, englishName, localizedName } country options.
 * The englishName is used as the value (for database consistency),
 * while localizedName is displayed to the user in their language.
 * Falls back gracefully if Intl.DisplayNames is unavailable.
 */
export function getCountryOptions(locale = "en") {
    try {
        // Get English names for values (database consistency)
        const englishDisplayNames =
            typeof Intl !== "undefined" && Intl.DisplayNames
                ? new Intl.DisplayNames(["en"], { type: "region" })
                : null;
        
        // Get localized names for display
        const localizedDisplayNames =
            typeof Intl !== "undefined" && Intl.DisplayNames
                ? new Intl.DisplayNames([locale], { type: "region" })
                : null;

        const options = countryCodes.map((code) => {
            const englishName = englishDisplayNames ? englishDisplayNames.of(code) : code;
            const localizedName = localizedDisplayNames ? localizedDisplayNames.of(code) : englishName;
            return { 
                code, 
                name: englishName || code,  // This will be the value
                displayName: localizedName || englishName || code  // This will be shown to user
            };
        });

        // Filter out any that didn't resolve to a readable name and sort alphabetically by display name
        return options
            .filter((opt) => typeof opt.name === "string" && opt.name.trim())
            .sort((a, b) => optCompare(a.displayName, b.displayName));
    } catch (e) {
        // Fallback: return codes as names if anything goes wrong
        return countryCodes.map((code) => ({ code, name: code, displayName: code }));
    }
}

function optCompare(a, b) {
    return a.localeCompare(b, undefined, { sensitivity: "base" });
}
